// Code generated by foptgen; DO NOT EDIT.
{{- $tree := .}}

package {{ $tree.PackageName }}

type {{ $tree.OptionTypeName }} func({{ $tree.StructName }}) {{ $tree.StructName }}

{{- range $optIdx, $opt := $tree.Options }}

func With{{ $opt.FieldName}}(v {{ $opt.FieldType }}) {{ $tree.OptionTypeName }} {
    return func(s {{ $tree.StructName }}) {{ $tree.StructName }} {
        s.{{ $opt.FieldName }} = v 
        return s 
    }
}
{{- end }}